deploy to maven (#1)
* deploy to maven

* only run on main

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -4,18 +4,48 @@
 #
 version: 2.1
 
-env: &env
-  TERM: dumb
-  CI: "true"
-  USER: circleci
-  TESTCONTAINERS_HOST_OVERRIDE: "localhost"
+executors:
+  nix:
+    docker:
+    - image: cimg/base:2022.02
+    environment:
+      USER: "circleci"
+      TERM: dumb
+      NIX_PROFILES: "/nix/var/nix/profiles/default /home/circleci/.nix-profile"
+      NIX_PATH: "/home/circleci/.nix-defexpr/channels"
+      NIX_SSL_CERT_FILE: "/etc/ssl/certs/ca-certificates.crt"
+      PATH: "/home/circleci/.nix-profile/bin:/home/circleci/bin:/home/circleci/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
+
+commands:
+  setup_nix:
+    description: Set up Nix
+    steps:
+    - run:
+        # We disable HTTP2 because `nix-channel --update` can sometimes fail with a segmentation fault.
+        # We disable sandboxing to avoid calls to `sethostname`, which is forbidden inside Docker.
+        name: Disable HTTP and sandboxing for Nix
+        command: |
+          mkdir -p ~/.config/nix
+          echo 'http2 = false' >> ~/.config/nix/nix.conf
+          echo 'sandbox = false' >> ~/.config/nix/nix.conf
+    - run:
+        name: Construct the Nix directory
+        command: |
+          sudo mkdir /nix
+          sudo chown $USER /nix
+    - run:
+        name: Install Nix
+        command: |
+          sh <(curl -fsSL https://nixos.org/nix/install) --no-daemon
+          . /home/circleci/.nix-profile/etc/profile.d/nix.sh
+          nix-shell shell.nix --run 'echo "Done loading all packages."'
 
 jobs:
   build:
     docker:
     - image: cimg/openjdk:11.0.13
     environment:
-      <<: *env
+      TESTCONTAINERS_HOST_OVERRIDE: "localhost"
     steps:
       - setup_remote_docker:
           version: 20.10.14
@@ -27,12 +57,45 @@ jobs:
           command: .circleci/autoforward.py
       - run:
           name: build
+          command: sbt test
+
+  release:
+    executor: nix
+    steps:
+      - checkout
+      - setup_nix
+      - run:
+          name: release
           command: |
             set -euo pipefail
 
-            sbt test
+            nix-shell --pure \
+                      --keep MAVEN_PASSWORD \
+                      --keep MAVEN_USERNAME \
+                      --keep gpg_code_signing \
+                      --run '
+                      set -euo pipefail
+
+                      export CI=true
+                      export CI_COMMIT_TAG=1
+                      export PGP_PASSPHRASE=""
+                      export PGP_SECRET="$gpg_code_signing"
+                      export SONATYPE_PASSWORD="$MAVEN_PASSWORD"
+                      export SONATYPE_USERNAME="$MAVEN_USERNAME"
+
+                      ./release.sh
+                      '
+
 workflows:
   version: 2
   build:
     jobs:
     - build
+    - release:
+        requires:
+        - build
+        context:
+        - npn-publish
+        filters:
+          branches:
+            only: main
